app_name: lfp.pay.api
group: api
# XXX Make sure all services with /transaction/ based routes have a weight LOWER than 1000
weight: 900
routes:
  1: ^/company/(.*)/penalties/late-filing
  2: ^/company/(.*)/penalties/late-filing.*
  3: ^/healthcheck/finance-system
